import { Duration } from "./notation";

export type Cell = {
  minDifficulty?: number;
  scaleDegs: number[];
  durs: Duration[];
  isRest?: boolean[];
  baseName: string;
};

export type CellUpgrade = {
  minDifficulty: number;
  scaleDegs: number[];
  durs: Duration[];
  isRest?: boolean[];
  baseName: string;
};

export const BASE_CELLS: Cell[] = [
  {
    baseName: "stepUp",
    scaleDegs: [0, 1, 2],
    durs: ["q", "q", "q"],
    minDifficulty: 1,
  },
  {
    baseName: "stepDown",
    scaleDegs: [0, -1, -2],
    durs: ["q", "q", "q"],
    minDifficulty: 1,
  },
  {
    baseName: "neighbor",
    scaleDegs: [0, 1, 0],
    durs: ["q", "q", "q"],
    minDifficulty: 1,
  },
  {
    baseName: "skip3rd",
    scaleDegs: [0, 2, 0],
    durs: ["q", "q", "q"],
    minDifficulty: 1,
  },
  {
    baseName: "walkUp",
    scaleDegs: [0, 1, 2, 3],
    durs: ["8", "8", "8", "8"],
    minDifficulty: 1,
  },
  {
    baseName: "bounce",
    scaleDegs: [0, 2, 1, 2],
    durs: ["q", "8", "8", "q"],
    minDifficulty: 1,
  },
  {
    baseName: "climb",
    scaleDegs: [0, 1, 2],
    durs: ["q", "8", "8"],
    minDifficulty: 1,
  },
  {
    baseName: "climbDown",
    scaleDegs: [0, -1, -2],
    durs: ["q", "8", "8"],
    minDifficulty: 1,
  },
  {
    baseName: "rest",
    scaleDegs: [0],
    durs: ["q"],
    minDifficulty: 1,
    isRest: [true],
  },
  {
    baseName: "pickup",
    scaleDegs: [0, 0],
    durs: ["8", "8"],
    minDifficulty: 2,
    isRest: [true, false],
  },
  {
    baseName: "sixth",
    scaleDegs: [-2],
    durs: ["q"],
    minDifficulty: 2,
  },
  {
    baseName: "root",
    scaleDegs: [0],
    durs: ["q"],
    minDifficulty: 1,
  },
  {
    baseName: "second",
    scaleDegs: [1],
    durs: ["q"],
    minDifficulty: 1,
  },
  {
    baseName: "fourth",
    scaleDegs: [3],
    durs: ["q"],
    minDifficulty: 1,
  },
  {
    baseName: "sus2",
    scaleDegs: [1, 0],
    durs: ["8", "8"],
    minDifficulty: 2,
  },
  {
    baseName: "skip8ths",
    scaleDegs: [3, 0],
    durs: ["8", "8"],
    minDifficulty: 2,
  },
  {
    baseName: "third",
    scaleDegs: [2],
    durs: ["q"],
    minDifficulty: 1,
  },
  {
    baseName: "easyWalk",
    scaleDegs: [1, 2],
    durs: ["8", "8"],
    minDifficulty: 2,
  },
  {
    baseName: "swing",
    scaleDegs: [0, 1, 0],
    durs: ["q.", "8", "q"],
    minDifficulty: 2,
  },
  {
    baseName: "breathe",
    scaleDegs: [0, 2, 0, 1],
    durs: ["q", "q", "q", "q"],
    isRest: [false, false, true, false],
    minDifficulty: 2,
  },
  {
    baseName: "arpegUp",
    scaleDegs: [0, 2, 4],
    durs: ["q", "q", "h"],
    minDifficulty: 2,
  },
  {
    baseName: "arpegDown",
    scaleDegs: [2, 0],
    durs: ["8", "8"],
    minDifficulty: 2,
  },
  {
    baseName: "cascade",
    scaleDegs: [4, 2, 1, 0],
    durs: ["8", "8", "8", "8"],
    minDifficulty: 3,
  },
  {
    baseName: "syncopate",
    scaleDegs: [0, 2, 1, 3],
    durs: ["8", "q", "8", "q"],
    minDifficulty: 3,
  },
  {
    baseName: "leap5th",
    scaleDegs: [0, 4, 2],
    durs: ["q", "q", "h"],
    minDifficulty: 4,
  },
  {
    baseName: "tripletRun",
    scaleDegs: [0, 1, 2],
    durs: ["8t", "8t", "8t"],
    minDifficulty: 4,
  },
  {
    baseName: "archUp",
    scaleDegs: [0, 2, 4, 2, 0],
    durs: ["8", "8", "q", "8", "8"],
    minDifficulty: 4,
  },
  {
    baseName: "flurry",
    scaleDegs: [0, 1, 2, 3, 2, 1],
    durs: ["16", "16", "16", "16", "q", "q"],
    minDifficulty: 5,
  },
];

export const CELL_UPGRADES: Record<string, CellUpgrade[]> = {
  stepUp: [
    {
      minDifficulty: 1,
      scaleDegs: [0, 2, 3],
      durs: ["q", "q", "q"],
      baseName: "stepUp",
    },
    {
      minDifficulty: 1,
      scaleDegs: [0, 1, 3],
      durs: ["q", "q", "q"],
      baseName: "stepUp",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, 1, 2],
      durs: ["q", "8", "q."],
      baseName: "stepUp",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, 2, 4],
      durs: ["q", "q", "q"],
      baseName: "stepUp",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 1, 2, 3],
      durs: ["8", "8", "q", "q"],
      baseName: "stepUp",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 1, 3],
      durs: ["q", "8", "8", "q"],
      baseName: "stepUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 1, 2, 3, 2],
      durs: ["8", "8", "8", "8", "q"],
      baseName: "stepUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 4, 5],
      durs: ["q", "8", "8", "q"],
      baseName: "stepUp",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 1, 2, -1, 0],
      durs: ["8t", "8t", "8t", "q", "q"],
      baseName: "stepUp",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 4, 7, 7],
      durs: ["8", "8", "8", "8", "q"],
      baseName: "stepUp",
    },
  ],
  stepDown: [
    {
      minDifficulty: 1,
      scaleDegs: [0, -2, -3],
      durs: ["q", "q", "q"],
      baseName: "stepDown",
    },
    {
      minDifficulty: 1,
      scaleDegs: [0, -1, -3],
      durs: ["q", "q", "q"],
      baseName: "stepDown",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, -2, -4],
      durs: ["q", "q", "q"],
      baseName: "stepDown",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, -1, -2],
      durs: ["q.", "8", "q"],
      baseName: "stepDown",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, -1, -2, -3],
      durs: ["8", "8", "q", "q"],
      baseName: "stepDown",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, -2, -1, -3],
      durs: ["q", "8", "8", "q"],
      baseName: "stepDown",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, -1, -2, -3, -2],
      durs: ["8", "8", "8", "8", "q"],
      baseName: "stepDown",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, -2, -3, -2],
      durs: ["8", "q", "8", "q"],
      baseName: "stepDown",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, -2, -4, -5],
      durs: ["q", "8", "8", "q"],
      baseName: "stepDown",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, -1, -2, 0, -1],
      durs: ["8t", "8t", "8t", "q", "q"],
      baseName: "stepDown",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, -2, -4, -7, -7],
      durs: ["8", "8", "8", "8", "q"],
      baseName: "stepDown",
    },
  ],
  neighbor: [
    {
      minDifficulty: 1,
      scaleDegs: [0, -1, 0],
      durs: ["q", "q", "q"],
      baseName: "neighbor",
    },
    {
      minDifficulty: 1,
      scaleDegs: [0, 2, 0],
      durs: ["q", "q", "q"],
      baseName: "neighbor",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 1, 0],
      durs: ["q", "8", "q."],
      baseName: "neighbor",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, 1, -1],
      durs: ["8", "8", "h"],
      baseName: "neighbor",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 1, -1, 0, -2],
      durs: ["8", "8", "8", "8", "q"],
      baseName: "neighbor",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 3, 2, 1, 0],
      durs: ["8", "8", "8", "8", "q"],
      baseName: "neighbor",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 1, 0],
      durs: ["q.", "16", "16", "q"],
      baseName: "neighbor",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 1, 2, 0, -1, 0],
      durs: ["8", "8", "8", "16", "16", "q"],
      baseName: "neighbor",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 1, 2, 1, 0],
      durs: ["8t", "8t", "8t", "q", "q"],
      baseName: "neighbor",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 1, 0, -1, 1, 0],
      durs: ["q", "16", "16", "16", "16", "q"],
      baseName: "neighbor",
    },
  ],
  skip3rd: [
    {
      minDifficulty: 1,
      scaleDegs: [0, -2, 0],
      durs: ["q", "q", "q"],
      baseName: "skip3rd",
    },
    {
      minDifficulty: 1,
      scaleDegs: [0, 2, 1],
      durs: ["q", "q", "q"],
      baseName: "skip3rd",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, 3, 0],
      durs: ["q", "q", "q"],
      baseName: "skip3rd",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 4],
      durs: ["q", "q", "q"],
      baseName: "skip3rd",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 0, 4, 0],
      durs: ["8", "8", "8", "8", "q"],
      baseName: "skip3rd",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 4, 0],
      durs: ["q", "q", "q"],
      baseName: "skip3rd",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 1, 0],
      durs: ["q", "8", "8", "q"],
      baseName: "skip3rd",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 4, 2, 4, 0],
      durs: ["q", "16", "16", "16", "16", "q"],
      baseName: "skip3rd",
    },
  ],
  walkUp: [
    {
      minDifficulty: 1,
      scaleDegs: [0, 1, 2, 4],
      durs: ["8", "8", "8", "8"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 1,
      scaleDegs: [0, -1, -2, -3],
      durs: ["8", "8", "8", "8"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 3,
      scaleDegs: [2, 3, 4, 3],
      durs: ["8", "8", "8", "8"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 3,
      scaleDegs: [1, 2, 3, 2],
      durs: ["8", "8", "8", "8"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 3, 5],
      durs: ["8", "8", "8", "8"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 1, 3, 4],
      durs: ["8", "8", "8", "8"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 3],
      durs: ["8", "q", "8"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 3,
      scaleDegs: [1, 2, 3],
      durs: ["qt", "qt", "qt"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 1, 2, 3, 1],
      durs: ["8", "8", "16", "16", "8"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [1, 2, 3, 4],
      durs: ["8t", "8t", "8t", "q"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [2, 3, 4, 5],
      durs: ["16", "16", "8", "q"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [1, 2, 3, 5, 7],
      durs: ["8t", "8t", "8t", "8", "8"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 1, 2, 3, 4],
      durs: ["8t", "8t", "8t", "8", "8"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 4, 5, 4],
      durs: ["16", "16", "16", "16", "q"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 1, 2, 1, 0, -1],
      durs: ["16", "16", "16", "16", "8", "8"],
      baseName: "walkUp",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 1, 2, 3, 4, 3, 2],
      durs: ["16", "16", "16", "16", "16", "16", "8"],
      baseName: "walkUp",
    },
  ],
  bounce: [
    {
      minDifficulty: 1,
      scaleDegs: [0, -2, -1, -2],
      durs: ["q", "8", "8", "q"],
      baseName: "bounce",
    },
    {
      minDifficulty: 1,
      scaleDegs: [0, 2, 0, 2],
      durs: ["q", "8", "8", "q"],
      baseName: "bounce",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, 3, 1, 3],
      durs: ["q", "8", "8", "q"],
      baseName: "bounce",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 1, 2, 3],
      durs: ["8", "8", "8", "8", "q"],
      baseName: "bounce",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 4, 2, 4],
      durs: ["q", "8", "8", "q"],
      baseName: "bounce",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 1, 2],
      durs: ["q.", "16", "16", "q"],
      baseName: "bounce",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 1, 3, 2],
      durs: ["q", "8", "16", "16", "q"],
      baseName: "bounce",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 1, 2, 0],
      durs: ["8t", "8t", "8t", "q", "q"],
      baseName: "bounce",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 5, 2, 5],
      durs: ["q", "8", "8", "q"],
      baseName: "bounce",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 1, 2, 4],
      durs: ["q", "8", "16", "16", "q"],
      baseName: "bounce",
    },
  ],
  climb: [
    {
      minDifficulty: 1,
      scaleDegs: [0, 1, 0],
      durs: ["q", "8", "8"],
      baseName: "climb",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, -1, 1],
      durs: ["8", "8", "q"],
      baseName: "climb",
    },
    {
      minDifficulty: 2,
      scaleDegs: [-1, 0, 1],
      durs: ["q", "8", "8"],
      baseName: "climb",
    },
    {
      minDifficulty: 2,
      scaleDegs: [1, 2, 3],
      durs: ["q", "8", "8"],
      baseName: "climb",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, -2, 1],
      durs: ["q", "8", "8"],
      baseName: "climb",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, -3, 3],
      durs: ["q", "8", "8"],
      baseName: "climb",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 4, 2, 0, -1],
      durs: ["8", "16", "8", "16", "8"],
      baseName: "climb",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 1, 0, -1, -2],
      durs: ["8", "16", "16", "16", "16", "8"],
      baseName: "climb",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 4, 5, 4, 2],
      durs: ["8", "16", "16", "8", "8"],
      baseName: "climb",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 3, 2, 1, 0, -1],
      durs: ["8", "16", "16", "16", "16", "8"],
      baseName: "climb",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, -1, 1, 0, 1],
      durs: ["8", "8", "16", "16", "8"],
      baseName: "climb",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, -1, 1, 2, 1],
      durs: ["8", "16", "16", "8", "8"],
      baseName: "climb",
    },
    {
      minDifficulty: 5,
      scaleDegs: [-4, 0, 4],
      durs: ["q", "8", "8"],
      baseName: "climb",
    },
  ],
  climbDown: [
    {
      minDifficulty: 1,
      scaleDegs: [-1, -2, -3],
      durs: ["q", "8", "8"],
      baseName: "climbDown",
    },
    {
      minDifficulty: 1,
      scaleDegs: [2, 1, 0],
      durs: ["q", "8", "8"],
      baseName: "climbDown",
    },
  ],
  pickup: [
    {
      minDifficulty: 2,
      scaleDegs: [0, 1],
      durs: ["8", "8"],
      baseName: "pickup",
      isRest: [true, false]
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, -1],
      durs: ["8", "8"],
      baseName: "pickup",
      isRest: [true, false]
    },
  ],
  skip8ths: [
    {
      minDifficulty: 2,
      scaleDegs: [-1, 2],
      durs: ["8", "8"],
      baseName: "skip8ths",
    },
    {
      minDifficulty: 2,
      scaleDegs: [-1, 3],
      durs: ["8", "8"],
      baseName: "skip8ths",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, 3],
      durs: ["8", "8"],
      baseName: "skip8ths",
    },
    {
      minDifficulty: 2,
      scaleDegs: [1, 4],
      durs: ["8", "8"],
      baseName: "skip8ths",
    },
    {
      minDifficulty: 2,
      scaleDegs: [4, 1],
      durs: ["8", "8"],
      baseName: "skip8ths",
    },
  ],
  swing: [
    {
      minDifficulty: 2,
      scaleDegs: [0, 2, 0],
      durs: ["q.", "8", "q"],
      baseName: "swing",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, 1, 2],
      durs: ["q.", "8", "q"],
      baseName: "swing",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, 2, 3],
      durs: ["q.", "8", "q"],
      baseName: "swing",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 1, 0],
      durs: ["q", "8.", "16", "q"],
      baseName: "swing",
    },
    {
      minDifficulty: 3,
      scaleDegs: [1, 4, 2, 0],
      durs: ["q", "8.", "16", "q"],
      baseName: "swing",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 3, 4],
      durs: ["q.", "8", "q"],
      baseName: "swing",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 4],
      durs: ["q.", "8", "q"],
      baseName: "swing",
    },
    {
      minDifficulty: 3,
      scaleDegs: [2, 4, 7],
      durs: ["q.", "8", "q"],
      baseName: "swing",
    },
    {
      minDifficulty: 4,
      scaleDegs: [2, 4, 5],
      durs: ["q.", "8", "q"],
      baseName: "swing",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 1, 2, 3],
      durs: ["q.", "16", "16", "q"],
      baseName: "swing",
    },
  ],
  breathe: [
    {
      minDifficulty: 2,
      scaleDegs: [0, 2, 0, 2],
      durs: ["q", "q", "q", "q"],
      isRest: [false, false, true, false],
      baseName: "breathe",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, 3, 0, 1],
      durs: ["q", "q", "q", "q"],
      isRest: [false, false, true, false],
      baseName: "breathe",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 4, 5],
      durs: ["q", "q", "q", "q"],
      isRest: [false, false, true, false],
      baseName: "breathe",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 0, -1],
      durs: ["q", "q", "q", "q"],
      isRest: [false, false, true, false],
      baseName: "breathe",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 2, 0, 0],
      durs: ["q", "8", "8", "q", "q"],
      isRest: [false, false, false, true, false],
      baseName: "breathe",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 4, 0, 2],
      durs: ["q", "q", "q", "q"],
      isRest: [false, false, true, false],
      baseName: "breathe",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 4, 0, 4],
      durs: ["q", "8", "8", "q", "q"],
      isRest: [false, false, false, true, false],
      baseName: "breathe",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 0, 1],
      durs: ["q.", "8", "q", "q"],
      isRest: [false, false, true, false],
      baseName: "breathe",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 5, 0, 1],
      durs: ["q", "q", "q", "q"],
      isRest: [false, false, true, false],
      baseName: "breathe",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 4, 7],
      durs: ["q", "q", "q", "q"],
      isRest: [false, false, true, false],
      baseName: "breathe",
    },
  ],
  arpegUp: [
    {
      minDifficulty: 2,
      scaleDegs: [0, -2, -4],
      durs: ["q", "q", "h"],
      baseName: "arpegUp",
    },
    {
      minDifficulty: 2,
      scaleDegs: [0, 2, 5],
      durs: ["q", "q", "h"],
      baseName: "arpegUp",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 4, 2],
      durs: ["q", "q", "q", "q"],
      baseName: "arpegUp",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 3, 5],
      durs: ["q", "q", "h"],
      baseName: "arpegUp",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 4, 2],
      durs: ["8", "8", "q", "h"],
      baseName: "arpegUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 4, 7],
      durs: ["q", "q", "q", "q"],
      baseName: "arpegUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 4, 5, 4],
      durs: ["8", "8", "8", "8", "h"],
      baseName: "arpegUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 4, 7],
      durs: ["q", "8", "8", "h"],
      baseName: "arpegUp",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 4, 7, 4],
      durs: ["8", "8", "8", "8", "h"],
      baseName: "arpegUp",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 4, 2, 0, 0],
      durs: ["16", "16", "16", "16", "q", "h"],
      baseName: "arpegUp",
    },
  ],
  cascade: [
    {
      minDifficulty: 3,
      scaleDegs: [-4, -2, -1, 0],
      durs: ["8", "8", "8", "8"],
      baseName: "cascade",
    },
    {
      minDifficulty: 3,
      scaleDegs: [5, 3, 2, 0],
      durs: ["8", "8", "8", "8"],
      baseName: "cascade",
    },
    {
      minDifficulty: 3,
      scaleDegs: [4, 2, 0, -1],
      durs: ["8", "8", "8", "8"],
      baseName: "cascade",
    },
    {
      minDifficulty: 4,
      scaleDegs: [3, 0, -1, -2],
      durs: ["8", "8", "8", "8"],
      baseName: "cascade",
    },
    {
      minDifficulty: 4,
      scaleDegs: [7, 4, 2, 0],
      durs: ["8", "8", "8", "8"],
      baseName: "cascade",
    },
    {
      minDifficulty: 4,
      scaleDegs: [4, 3, 2, 1, 0],
      durs: ["16", "16", "16", "16", "q"],
      baseName: "cascade",
    },
    {
      minDifficulty: 5,
      scaleDegs: [5, 4, 2, 1, 0],
      durs: ["16", "16", "16", "16", "q"],
      baseName: "cascade",
    },
    {
      minDifficulty: 5,
      scaleDegs: [4, 2, 1, 0, -2],
      durs: ["16", "16", "16", "16", "q"],
      baseName: "cascade",
    },
  ],
  syncopate: [
    {
      minDifficulty: 3,
      scaleDegs: [0, -2, -1, -3],
      durs: ["8", "q", "8", "q"],
      baseName: "syncopate",
    },
    {
      minDifficulty: 3,
      scaleDegs: [0, 2, 0, 2],
      durs: ["8", "q", "8", "q"],
      baseName: "syncopate",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 3, 1, 4],
      durs: ["8", "q", "8", "q"],
      baseName: "syncopate",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 1, 3],
      durs: ["8", "q.", "8.", "16"],
      baseName: "syncopate",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 4, 2, 5],
      durs: ["8", "q", "8", "q"],
      baseName: "syncopate",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 4, 7],
      durs: ["8", "q", "8", "q"],
      baseName: "syncopate",
    },
  ],
  leap5th: [
    {
      minDifficulty: 4,
      scaleDegs: [0, -4, -2],
      durs: ["q", "q", "h"],
      baseName: "leap5th",
    },
    {
      minDifficulty: 4,
      scaleDegs: [-1, 4, 3],
      durs: ["q", "q", "h"],
      baseName: "leap5th",
    },
    {
      minDifficulty: 4,
      scaleDegs: [1, 5, 4],
      durs: ["q", "q", "h"],
      baseName: "leap5th",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 4, 2, 0],
      durs: ["q", "q", "q", "q"],
      baseName: "leap5th",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 4, 2, 3, 4],
      durs: ["q", "q", "8", "8", "q"],
      baseName: "leap5th",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 7, 4],
      durs: ["q", "q", "h"],
      baseName: "leap5th",
    },
    {
      minDifficulty: 5,
      scaleDegs: [6, 5, 4],
      durs: ["q", "q", "h"],
      baseName: "leap5th",
    },
    {
      minDifficulty: 5,
      scaleDegs: [-1, 0, 4, 3, 2, 1],
      durs: ["8", "8", "q", "8", "q", "8"],
      baseName: "leap5th",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 7, 6, 5, 4, 3],
      durs: ["q", "16", "16", "16", "16", "h"],
      baseName: "leap5th",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 4, 5, 4, 2],
      durs: ["q", "q", "8", "8", "q"],
      baseName: "leap5th",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 4, 7],
      durs: ["q", "q", "h"],
      baseName: "leap5th",
    },
  ],
  tripletRun: [
    {
      minDifficulty: 4,
      scaleDegs: [0, -1, -2],
      durs: ["8t", "8t", "8t"],
      baseName: "tripletRun",
    },
    {
      minDifficulty: 4,
      scaleDegs: [1, 2, 4],
      durs: ["8t", "8t", "8t"],
      baseName: "tripletRun",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 1, 3],
      durs: ["8t", "8t", "8t"],
      baseName: "tripletRun",
    },
    {
      minDifficulty: 4,
      scaleDegs: [2, 1, 0],
      durs: ["8t", "8t", "8t"],
      baseName: "tripletRun",
    },
    {
      minDifficulty: 4,
      scaleDegs: [1, 0, -1],
      durs: ["8t", "8t", "8t"],
      baseName: "tripletRun",
    },
    {
      minDifficulty: 4,
      scaleDegs: [2, 3, 5],
      durs: ["8t", "8t", "8t"],
      baseName: "tripletRun",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 1],
      durs: ["8t", "8t", "8t"],
      baseName: "tripletRun",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 1, 0],
      durs: ["8t", "8t", "8t"],
      baseName: "tripletRun",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 3, 5],
      durs: ["8t", "8t", "8t"],
      baseName: "tripletRun",
    },
    {
      minDifficulty: 5,
      scaleDegs: [4, 2, 0],
      durs: ["8t", "8t", "8t"],
      baseName: "tripletRun",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 3],
      durs: ["8t", "8t", "8t"],
      baseName: "tripletRun",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 4, 2],
      durs: ["8t", "8t", "8t"],
      baseName: "tripletRun",
    },
  ],
  flurry: [
    {
      minDifficulty: 5,
      scaleDegs: [0, -1, -2, -3, -2, -1],
      durs: ["16", "16", "16", "16", "q", "q"],
      baseName: "flurry",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 3, 4, 2, 1],
      durs: ["16", "16", "16", "16", "q", "q"],
      baseName: "flurry",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 1, 2, 4, 2, 1],
      durs: ["16", "16", "16", "16", "q", "q"],
      baseName: "flurry",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 1, 2, 3, 4, 3],
      durs: ["16", "16", "16", "16", "q", "q"],
      baseName: "flurry",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 1, 2, 3, 2, 0],
      durs: ["16", "16", "16", "16", "q", "q"],
      baseName: "flurry",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 4, 5, 4, 2],
      durs: ["16", "16", "16", "16", "q", "q"],
      baseName: "flurry",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 1, 3, 4, 3, 1],
      durs: ["16", "16", "16", "16", "q", "q"],
      baseName: "flurry",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 1, 2, 3, 4, 5],
      durs: ["16", "16", "16", "16", "q", "q"],
      baseName: "flurry",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 1, 3, 2, 1],
      durs: ["16", "16", "16", "16", "q", "q"],
      baseName: "flurry",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 1, 2, 4, 5, 4],
      durs: ["16", "16", "16", "16", "q", "q"],
      baseName: "flurry",
    },
  ],
  archUp: [
    {
      minDifficulty: 4,
      scaleDegs: [0, -2, -4, -2, 0],
      durs: ["8", "8", "q", "8", "8"],
      baseName: "archUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 5, 2, 0],
      durs: ["8", "8", "q", "8", "8"],
      baseName: "archUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 2, 4, 3, 0],
      durs: ["8", "8", "q", "8", "8"],
      baseName: "archUp",
    },
    {
      minDifficulty: 4,
      scaleDegs: [0, 3, 5, 3, 0],
      durs: ["8", "8", "q", "8", "8"],
      baseName: "archUp",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 7, 2, 0],
      durs: ["8", "8", "q", "8", "8"],
      baseName: "archUp",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 4, 5, 4, 2, 0],
      durs: ["16", "16", "16", "16", "8", "8", "q"],
      baseName: "archUp",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 2, 4, 2, 0],
      durs: ["8t", "8t", "8t", "q", "q"],
      baseName: "archUp",
    },
    {
      minDifficulty: 5,
      scaleDegs: [0, 4, 7, 4, 0],
      durs: ["8", "8", "q", "8", "8"],
      baseName: "archUp",
    },
  ],
};
