import { Duration } from "./notation"

export type Cell = {
  name: string
  relSteps: number[]
  durs: Duration[]
  isRest?: boolean[],
  minDifficulty?: number,
}

export type CellUpgrade = {
  minDifficulty: number
  relSteps: number[]
  durs: Duration[]
  isRest?: boolean[]
}

export const BASE_CELLS: Cell[] = [
  { 
    name: "stepUp",
    relSteps: [0, 1, 2],
    durs: ['q', 'q', 'q'],
    minDifficulty: 1,
  },
  { 
    name: "stepDown",
    relSteps: [0, -1, -2],
    durs: ['q', 'q', 'q'],
    minDifficulty: 1,
  },
  { 
    name: "neighbor",
    relSteps: [0, 1, 0],
    durs: ['q', 'q', 'q'],
    minDifficulty: 1,
  },
  { 
    name: "skip3rd",
    relSteps: [0, 2, 0],
    durs: ['q', 'q', 'q'],
    minDifficulty: 1,
  },
  { 
    name: "walkUp",
    relSteps: [0, 1, 2, 3],
    durs: ['8', '8', '8', '8'],
    minDifficulty: 1,
  },
  { 
    name: "bounce",
    relSteps: [0, 2, 1, 2],
    durs: ['q', '8', '8', 'q'],
    minDifficulty: 1,
  },
  { 
    name: "rockStep",
    relSteps: [0, -1, 1],
    durs: ['q', '8', '8'],
    minDifficulty: 1,
  },
  { 
    name: "swing",
    relSteps: [0, 1, 2, 3],
    durs: ['q.', '8', 'q'],
    minDifficulty: 2,
  },
  { 
    name: "breathe",
    relSteps: [0, 2, 0, 1],
    durs: ['q', 'q', 'q', 'q'],
    isRest: [false, false, true, false],
    minDifficulty: 2,
  },
  { 
    name: "arpegUp",
    relSteps: [0, 2, 4],
    durs: ['q', 'q', 'h'],
    minDifficulty: 2,
  },
  { 
    name: "cascade",
    relSteps: [4, 2, 1, 0],
    durs: ['8', '8', '8', '8'],
    minDifficulty: 3,
  },
  { 
    name: "syncopate",
    relSteps: [0, 2, 1, 3],
    durs: ['8', 'q', '8', 'q'],
    minDifficulty: 3,
  },
  { 
    name: "leap5th",
    relSteps: [0, 4, 2],
    durs: ['q', 'q', 'h'],
    minDifficulty: 4,
  },
  { 
    name: "tripletRun",
    relSteps: [0, 1, 2],
    durs: ['8t', '8t', '8t'],
    minDifficulty: 4,
},
{ 
  name: "archUp",
  relSteps: [0, 2, 4, 2, 0],
  durs: ['8', '8', 'q', '8', '8'],
  minDifficulty: 4,
},
{ 
  name: "flurry",
  relSteps: [0, 1, 2, 3, 2, 1],
  durs: ['16', '16', '16', '16', 'q', 'q'],
  minDifficulty: 5,
},
  
];

export const CELL_UPGRADES: Record<string, CellUpgrade[]> = {
  stepUp: [
    { minDifficulty: 1, relSteps: [0, 2, 3], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 1, relSteps: [0, 1, 3], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 2, relSteps: [0, 1, 2], durs: ['q', '8', 'q.'] }, 
    { minDifficulty: 2, relSteps: [0, 2, 4], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 1, 2, 3], durs: ['8', '8', 'q', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 2, 1, 3], durs: ['q', '8', '8', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 1, 2, 3, 2], durs: ['8', '8', '8', '8', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 4, 5], durs: ['q', '8', '8', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 1, 2], durs: ['8t', '8t', '8t', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4, 7], durs: ['8', '8', '8', '8', 'q'] }, 
  ],
  stepDown: [
    { minDifficulty: 1, relSteps: [0, -2, -3], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 1, relSteps: [0, -1, -3], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 2, relSteps: [0, -2, -4], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 2, relSteps: [0, -1, -2], durs: ['q.', '8', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, -1, -2, -3], durs: ['8', '8', 'q', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, -2, -1, -3], durs: ['q', '8', '8', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, -1, -2, -3, -2], durs: ['8', '8', '8', '8', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, -2, -4, -5], durs: ['q', '8', '8', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, -1, -2], durs: ['8t', '8t', '8t', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, -2, -4, -7], durs: ['8', '8', '8', '8', 'q'] }, 
  ],
  neighbor: [
    { minDifficulty: 1, relSteps: [0, -1, 0], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 1, relSteps: [0, 2, 0], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 2, relSteps: [0, 1, 0], durs: ['q', '8', 'q.'] }, 
    { minDifficulty: 2, relSteps: [0, 1, -1, 0], durs: ['8', '8', '8', '8', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 2, 1, 0], durs: ['8', '8', '8', '8', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 1, 0], durs: ['q.', '16', '16', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 0, -1, 0], durs: ['8', '8', '8', '16', '16', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 3, 0], durs: ['q', '16', '16', '16', '16', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 1, 2, 1, 0], durs: ['8t', '8t', '8t', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 4, 0], durs: ['q', '16', '16', '16', '16', 'q'] }, 
  ],
  skip3rd: [
    { minDifficulty: 1, relSteps: [0, -2, 0], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 1, relSteps: [0, 2, 1], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 2, relSteps: [0, 3, 0], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 2, relSteps: [0, 2, 0], durs: ['q.', '8', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 2, 4], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 2, 0, 4], durs: ['8', '8', '8', '8', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 4, 0], durs: ['q', 'q', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 1, 0], durs: ['q', '8', '8', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4, 2, 0], durs: ['8t', '8t', '8t', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 5, 0], durs: ['q', '16', '16', '16', '16', 'q'] }, 
  ],
  walkUp: [
    { minDifficulty: 1, relSteps: [0, 1, 2, 4], durs: ['8', '8', '8', '8'] }, 
    { minDifficulty: 1, relSteps: [0, -1, -2, -3], durs: ['8', '8', '8', '8'] }, 
    { minDifficulty: 2, relSteps: [0, 1, 2, 3], durs: ['8', '8', '16', '16', '8'] }, 
    { minDifficulty: 2, relSteps: [0, 2, 3, 5], durs: ['8', '8', '8', '8'] }, 
    { minDifficulty: 3, relSteps: [0, 1, 3, 4], durs: ['8', '8', '8', '8'] }, 
    { minDifficulty: 3, relSteps: [0, 1, 2, 3, 2], durs: ['16', '16', '16', '16', '8', '8'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 4, 5, 4], durs: ['16', '16', '16', '16', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 1, 2, 3], durs: ['8t', '8t', '8t', '8', '8'] }, 
    { minDifficulty: 5, relSteps: [0, 1, 2, 3, 4, 5], durs: ['16', '16', '16', '16', '16', '16', '8'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4, 7], durs: ['16', '16', '16', '16', 'q'] }, 
  ],
  bounce: [
    { minDifficulty: 1, relSteps: [0, -2, -1, -2], durs: ['q', '8', '8', 'q'] }, 
    { minDifficulty: 1, relSteps: [0, 2, 0, 2], durs: ['q', '8', '8', 'q'] }, 
    { minDifficulty: 2, relSteps: [0, 3, 1, 3], durs: ['q', '8', '8', 'q'] }, 
    { minDifficulty: 2, relSteps: [0, 2, 1, 2], durs: ['q.', '16', '16', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 2, 1, 2, 3], durs: ['8', '8', '8', '8', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 4, 2, 4], durs: ['q', '8', '8', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 1, 3, 2], durs: ['q', '8', '16', '16', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 1, 2], durs: ['8t', '8t', '8t', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 5, 2, 5], durs: ['q', '8', '8', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 1, 2, 4], durs: ['q', '8', '16', '16', 'q'] }, 
  ],
  rockStep: [
    { minDifficulty: 1, relSteps: [0, 1, -1], durs: ['q', '8', '8'] }, 
    { minDifficulty: 1, relSteps: [0, -2, 2], durs: ['q', '8', '8'] }, 
    { minDifficulty: 2, relSteps: [0, -1, 1], durs: ['8', '8', 'q'] }, 
    { minDifficulty: 2, relSteps: [0, -1, 1, 0], durs: ['8', '8', '16', '16', '8'] }, 
    { minDifficulty: 3, relSteps: [0, -2, 1], durs: ['q', '8', '8'] }, 
    { minDifficulty: 3, relSteps: [0, -1, 1, 2], durs: ['8', '16', '16', '8', '8'] }, 
    { minDifficulty: 4, relSteps: [0, -3, 3], durs: ['q', '8', '8'] }, 
    { minDifficulty: 4, relSteps: [0, -1, 0, 1], durs: ['8', '16', '16', '16', '16', '8'] }, 
    { minDifficulty: 5, relSteps: [0, -2, 1], durs: ['8t', '8t', '8t', '8', '8'] }, 
    { minDifficulty: 5, relSteps: [0, -4, 4], durs: ['q', '8', '8'] }, 
  ],
  swing: [
    { minDifficulty: 2, relSteps: [0, -1, -2, -3], durs: ['q.', '8', 'q'] }, 
    { minDifficulty: 2, relSteps: [0, 2, 3, 5], durs: ['q.', '8', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 1, 2, 3], durs: ['q', '8.', '16', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 1, 3, 4], durs: ['q.', '8', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 1, 2, 4], durs: ['q.', '8', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 4, 5], durs: ['q.', '8', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 1, 2, 3], durs: ['q.', '16', '16', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 1, 2, 3, 2], durs: ['q', '16', '16', '8', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4, 7], durs: ['q.', '8', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 1, 2, 3, 4], durs: ['8.', '16', '16', '16', '8', 'q'] }, 
  ],
  breathe: [
    { minDifficulty: 2, relSteps: [0, 2, 0, 2], durs: ['q', 'q', 'q', 'q'], isRest: [false, false, true, false] }, 
    { minDifficulty: 2, relSteps: [0, 3, 0, 1], durs: ['q', 'q', 'q', 'q'], isRest: [false, false, true, false] }, 
    { minDifficulty: 3, relSteps: [0, 2, 4, 5], durs: ['q', 'q', 'q', 'q'], isRest: [false, false, true, false] }, 
    { minDifficulty: 3, relSteps: [0, 2, 0, -1], durs: ['q', 'q', 'q', 'q'], isRest: [false, false, true, false] }, 
    { minDifficulty: 3, relSteps: [0, 2, 0, 1], durs: ['q', '8', '8', 'q', 'q'], isRest: [false, false, false, true, false] }, 
    { minDifficulty: 4, relSteps: [0, 4, 0, 2], durs: ['q', 'q', 'q', 'q'], isRest: [false, false, true, false] }, 
    { minDifficulty: 4, relSteps: [0, 2, 1, 3], durs: ['q', '8', '8', 'q', 'q'], isRest: [false, false, false, true, false] }, 
    { minDifficulty: 4, relSteps: [0, 2, 0, 1], durs: ['q.', '8', 'q', 'q'], isRest: [false, false, true, false] }, 
    { minDifficulty: 5, relSteps: [0, 5, 0, 1], durs: ['q', 'q', 'q', 'q'], isRest: [false, false, true, false] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4, 7], durs: ['q', 'q', 'q', 'q'], isRest: [false, false, true, false] }, 
  ],
  arpegUp: [
    { minDifficulty: 2, relSteps: [0, -2, -4], durs: ['q', 'q', 'h'] }, 
    { minDifficulty: 2, relSteps: [0, 2, 5], durs: ['q', 'q', 'h'] }, 
    { minDifficulty: 3, relSteps: [0, 2, 4, 2], durs: ['q', 'q', 'q', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 3, 5], durs: ['q', 'q', 'h'] }, 
    { minDifficulty: 3, relSteps: [0, 2, 4], durs: ['8', '8', 'q', 'h'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 4, 7], durs: ['q', 'q', 'q', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 4, 5, 4], durs: ['8', '8', '8', '8', 'h'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 4], durs: ['q', '8', '8', 'h'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4, 7, 4], durs: ['8', '8', '8', '8', 'h'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4], durs: ['16', '16', '16', '16', 'q', 'h'] }, 
  ],
  cascade: [
    { minDifficulty: 3, relSteps: [-4, -2, -1, 0], durs: ['8', '8', '8', '8'] }, 
    { minDifficulty: 3, relSteps: [5, 3, 2, 0], durs: ['8', '8', '8', '8'] }, 
    { minDifficulty: 3, relSteps: [4, 2, 0, -1], durs: ['8', '8', '8', '8'] }, 
    { minDifficulty: 4, relSteps: [4, 2, 1, 0], durs: ['8', '16', '16', '8', '8'] }, 
    { minDifficulty: 4, relSteps: [7, 4, 2, 0], durs: ['8', '8', '8', '8'] }, 
    { minDifficulty: 4, relSteps: [4, 3, 2, 1, 0], durs: ['16', '16', '16', '16', 'q'] }, 
    { minDifficulty: 5, relSteps: [5, 4, 2, 1, 0], durs: ['16', '16', '16', '16', 'q'] }, 
    { minDifficulty: 5, relSteps: [4, 2, 1, 0], durs: ['8t', '8t', '8t', '8', '8'] }, 
    { minDifficulty: 5, relSteps: [7, 5, 4, 2, 1, 0], durs: ['16', '16', '16', '16', '16', '16', '8'] }, 
    { minDifficulty: 5, relSteps: [4, 2, 1, 0, -2], durs: ['16', '16', '16', '16', 'q'] }, 
  ],
  syncopate: [
    { minDifficulty: 3, relSteps: [0, -2, -1, -3], durs: ['8', 'q', '8', 'q'] }, 
    { minDifficulty: 3, relSteps: [0, 2, 0, 2], durs: ['8', 'q', '8', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 3, 1, 4], durs: ['8', 'q', '8', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 1, 3], durs: ['8', 'q.', '8.', '16'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 1, 3, 2], durs: ['8', '8', '8', '16', '16', 'q'] }, 
    { minDifficulty: 4, relSteps: [0, 4, 2, 5], durs: ['8', 'q', '8', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 1, 3], durs: ['16', '16', 'q', '8', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4, 7], durs: ['8', 'q', '8', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 1, 3, 5], durs: ['8t', '8t', '8t', '8', 'q', '8'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 1, 3, 4], durs: ['16', '16', 'q', '16', '16', 'q'] }, 
  ],
  leap5th: [
    { minDifficulty: 4, relSteps: [0, -4, -2], durs: ['q', 'q', 'h'] }, 
    { minDifficulty: 4, relSteps: [0, 4, 3], durs: ['q', 'q', 'h'] }, 
    { minDifficulty: 4, relSteps: [0, 5, 3], durs: ['q', 'q', 'h'] }, 
    { minDifficulty: 4, relSteps: [0, 4, 2], durs: ['8', '8', 'q', 'h'] }, 
    { minDifficulty: 4, relSteps: [0, 4, 2, 0], durs: ['q', 'q', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 7, 4], durs: ['q', 'q', 'h'] }, 
    { minDifficulty: 5, relSteps: [0, 4, 2, 4], durs: ['q', 'q', '8', '8', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 4, 2], durs: ['q', '16', '16', '16', '16', 'h'] }, 
    { minDifficulty: 5, relSteps: [0, 4, 5, 4, 2], durs: ['q', 'q', '8', '8', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 4, 7], durs: ['q', 'q', 'h'] }, 
  ],
  tripletRun: [
    { minDifficulty: 4, relSteps: [0, -1, -2], durs: ['8t', '8t', '8t'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 4], durs: ['8t', '8t', '8t'] }, 
    { minDifficulty: 4, relSteps: [0, 1, 3], durs: ['8t', '8t', '8t'] }, 
    { minDifficulty: 4, relSteps: [2, 1, 0], durs: ['8t', '8t', '8t'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 1], durs: ['8t', '8t', '8t'] }, 
    { minDifficulty: 5, relSteps: [0, 1, 0], durs: ['8t', '8t', '8t'] }, 
    { minDifficulty: 5, relSteps: [0, 3, 5], durs: ['8t', '8t', '8t'] }, 
    { minDifficulty: 5, relSteps: [4, 2, 0], durs: ['8t', '8t', '8t'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 3], durs: ['8t', '8t', '8t'] }, 
    { minDifficulty: 5, relSteps: [0, 4, 2], durs: ['8t', '8t', '8t'] }, 
  ],
  flurry: [
    { minDifficulty: 5, relSteps: [0, -1, -2, -3, -2, -1], durs: ['16', '16', '16', '16', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 3, 4, 2, 1], durs: ['16', '16', '16', '16', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 1, 2, 4, 2, 1], durs: ['16', '16', '16', '16', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 1, 2, 3, 4, 3], durs: ['16', '16', '16', '16', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 1, 2, 3, 2, 0], durs: ['16', '16', '16', '16', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4, 5, 4, 2], durs: ['16', '16', '16', '16', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 1, 3, 4, 3, 1], durs: ['16', '16', '16', '16', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 1, 2, 3, 4, 5], durs: ['16', '16', '16', '16', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 1, 3, 2, 1], durs: ['16', '16', '16', '16', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 1, 2, 4, 5, 4], durs: ['16', '16', '16', '16', 'q', 'q'] }, 
  ],
  archUp: [
    { minDifficulty: 4, relSteps: [0, -2, -4, -2, 0], durs: ['8', '8', 'q', '8', '8'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 5, 2, 0], durs: ['8', '8', 'q', '8', '8'] }, 
    { minDifficulty: 4, relSteps: [0, 2, 4, 3, 0], durs: ['8', '8', 'q', '8', '8'] }, 
    { minDifficulty: 4, relSteps: [0, 3, 5, 3, 0], durs: ['8', '8', 'q', '8', '8'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4, 2, 0], durs: ['8', '16', '16', 'q', '8', '8'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4, 2, 0], durs: ['8', '8', 'q', '16', '16', '8'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 7, 2, 0], durs: ['8', '8', 'q', '8', '8'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4, 5, 4, 2, 0], durs: ['16', '16', '16', '16', '8', '8', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 2, 4, 2, 0], durs: ['8t', '8t', '8t', 'q', 'q'] }, 
    { minDifficulty: 5, relSteps: [0, 4, 7, 4, 0], durs: ['8', '8', 'q', '8', '8'] }, 
  ],
};